// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggK5PMfBxJt0Fw94232eKT3fViKgrHp0',
    appId: '1:634883294921:web:b25a6a7697cd97f05def18',
    messagingSenderId: '634883294921',
    projectId: 'seguridad-prueba-80d54',
    authDomain: 'seguridad-prueba-80d54.firebaseapp.com',
    storageBucket: 'seguridad-prueba-80d54.firebasestorage.app',
    measurementId: 'G-YY3RZBDYVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUKc-yRxZ7xYxSeFekkTgW8yTFLCXSGI',
    appId: '1:634883294921:android:77bc6a89a28ea0685def18',
    messagingSenderId: '634883294921',
    projectId: 'seguridad-prueba-80d54',
    storageBucket: 'seguridad-prueba-80d54.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggK5PMfBxJt0Fw94232eKT3fViKgrHp0',
    appId: '1:634883294921:web:789851fff8be96da5def18',
    messagingSenderId: '634883294921',
    projectId: 'seguridad-prueba-80d54',
    authDomain: 'seguridad-prueba-80d54.firebaseapp.com',
    storageBucket: 'seguridad-prueba-80d54.firebasestorage.app',
    measurementId: 'G-JN80Q40NV6',
  );
}
